### ISSUE TITLE
Incorrect paper link in the project page

### ISSUE THREAD

**Issue by costrice** [g3956/PRM#1]
Hi. just want to remind the authors that the “paper” button in the project website (https://wenhangge.github.io/PRM/) redirects to a wrong arxiv page ([LucidFusion](https://arxiv.org/abs/2410.15636), but it should be your [PRM](https://arxiv.org/abs/2412.07371)).

**Comment by g3956** [comment]
Thank you for your reminder, we have already corrected it.
